In [144]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_moons

X, y = make_moons(n_samples=500, noise=0.3, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [145]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

log_clf = LogisticRegression(random_state=42, solver='lbfgs')
rnd_clf = RandomForestClassifier(n_estimators=100, random_state=42)
svc_clf = SVC(gamma='scale', random_state=42)

voting_clf = VotingClassifier(
    estimators=[('lr', log_clf), ('rnd', rnd_clf), ('svc', svc_clf)], 
    voting = 'hard'
)

In [146]:
voting_clf.fit(X_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(random_state=42)),
                             ('rnd', RandomForestClassifier(random_state=42)),
                             ('svc', SVC(random_state=42))])

In [147]:
from sklearn.metrics import accuracy_score

# predictions = voting_clf.predict(X_test)

# print(accuracy_score(predictions, y_test))

for clf in (log_clf, rnd_clf, svc_clf, voting_clf):
    clf.fit(X_train, y_train)
    predictions = clf.predict(X_test)
    print(clf.__class__.__name__, accuracy_score(predictions, y_test))

LogisticRegression 0.864
RandomForestClassifier 0.896
SVC 0.896
VotingClassifier 0.912


In [148]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

bag_clf = BaggingClassifier(
    DecisionTreeClassifier(), n_estimators=500,
    bootstrap=True, random_state=42
    )

In [149]:
bag_clf.fit(X_train, y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=500,
                  random_state=42)

In [150]:
predictions2 = bag_clf.predict(X_test)

print(accuracy_score(predictions2, y_test))

0.92


In [151]:
# pasting when bootstrap set to False
bag_clf = BaggingClassifier(
    DecisionTreeClassifier(), n_estimators=500,
    bootstrap=False, random_state=42
    )

In [152]:
from sklearn.ensemble import RandomForestClassifier

rnd_clf = RandomForestClassifier(n_estimators=500, max_leaf_nodes=16, random_state=42)
rnd_clf.fit(X_train, y_train)
y_pred_random = rnd_clf.predict(X_test)

print(accuracy_score(y_pred_random, y_test))

0.912


In [153]:
from sklearn.datasets import load_iris

iris = load_iris()

rnd_clf = RandomForestClassifier(n_estimators=100, random_state=42)

rnd_clf.fit(iris['data'], iris['target'])

RandomForestClassifier(random_state=42)

In [154]:
rnd_clf.feature_importances_

array([0.10612762, 0.02167809, 0.43612951, 0.43606478])

In [155]:
from sklearn.ensemble import AdaBoostClassifier


ada_clf = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=1), n_estimators=200, learning_rate=0.5, random_state=42
)

In [156]:
ada_clf.fit(X_train, y_train)

y_pred_ada = ada_clf.predict(X_test)

print(accuracy_score(y_pred_ada, y_test))

0.896


In [157]:
import numpy as np

X = np.random.rand(100, 1) - 0.5
y = 3 * X[:, 0]**2 + 0.05 * np.random.randn(100)

#from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor

In [158]:
tree_reg1 = DecisionTreeRegressor(max_depth=16)

tree_reg1.fit(X, y)

DecisionTreeRegressor(max_depth=16)

In [159]:
y2 = y - tree_reg1.predict(X)

tree_reg2 = DecisionTreeRegressor(max_depth=16)
tree_reg2.fit(X, y2)

DecisionTreeRegressor(max_depth=16)

In [160]:
y3 = y2 - tree_reg2.predict(X)

tree_reg3 = DecisionTreeRegressor(max_depth=16)
tree_reg3.fit(X, y3)

DecisionTreeRegressor(max_depth=16)

In [161]:
X_new = np.array([[0.8]])

In [162]:
y_pred_gradient = tree_reg3.predict(X_new)
y_pred_gradient

array([0.])

In [163]:
a = 3 * 0.8 ** 2 + 0.05

In [164]:
y_pred_gradient = sum(tree.predict(X_new) for tree in (tree_reg1, tree_reg2, tree_reg3))
y_pred_gradient

array([0.83410618])